modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havenksh"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.havenksh]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="jei"
    mandatory=false
    versionRange="[15.0.0.12,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="jade"
    mandatory=true
    versionRange="[11.7.0,)"
    ordering="NONE"
    side="BOTH"