modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havenksh"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.havenksh]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="jei"
    type="optional"
    versionRange="[15.0.0.12,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="roughlyenoughitems"
    type="optional"
    versionRange="[16.0.788,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="jade"
    versionRange="[11.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="curios"
    type="required"
    versionRange="[9.2.0,)"
    ordering="NONE"
    side="BOTH"